jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Git Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 1.8
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      name: Build with Maven
      run: mvn clean deploy --batch-mode -DskipTests -Pdeploy -B -U -e
name: Maven Publish
on:
  repository_dispatch:
    types: trigger-ga___mvn_publish.yml
